# Generated by Django 5.2.6 on 2025-10-15 19:18

import django.core.validators
import dottify.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, default='default_cover.jpg', help_text='Optional cover art; uses a default image if not provided.', null=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('999.99'))])),
                ('release_date', models.DateField(validators=[dottify.models.validate_release_date])),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('format', models.CharField(blank=True, choices=[('SNGL', 'Single'), ('RMST', 'Remaster'), ('DLUX', 'Deluxe Edition'), ('COMP', 'Compilation'), ('LIVE', 'Live Recording')], max_length=4, null=True)),
            ],
            options={
                'ordering': ['artist_name', 'title'],
                'constraints': [models.UniqueConstraint(fields=('title', 'artist_name', 'format'), name='unique_album_title_per_artist_and_format')],
            },
        ),
    ]
