# Generated by Django 5.2.6 on 2025-10-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0002_comment_dottifyuser_playlist_rating_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default='no_cover.jpg', help_text='Optional cover art; uses a default image if not provided.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
